* Final Project

** Proposal Form

Once you've read the specification for the project (below) and decide on your topic, fill out this form
so that the instructor can provide feedback and ultimately approve
your project.

Once approved, your project will be listed in the "Selected Projects"
section below.

Link: [link to be published]


** Selected Projects
| Team member 1 | Team member 2 | Project                |
|---------------------+------------------+------------------------|
|

** Specification


*Select and explore a topic relevant to Ethical CS (to be approved by the instructor).* 


Create a presentation and paper giving an overview of the issue, why
it should be addressed, and possible solutions. The presentation
should include program-based examples illustrating the problem and
where appropriate to address solutions.Depending on topic, each team
may de/emphasize different portions.

Each project must also include a code component - that is a program
related to the topic. 


*Groups:* This is a team project. You should work with a single
 partner.

 There is no set length for the paper but the presentation slides,
 which should summarize the project should be able to be presented in
 30 minutes. As the final project is 25% of the grade, it should be of
 an appropriate depth and complexity.

GUIDING GOAL: Leave your classmates with something they can
incorporate into their own praxis. This could be a turn-key day/unit
plan, can include code snippets or full working programs, or something more
abstract. You know your audience...

** Grading

(Subject to change, prior to project delivery.)

*Rubric:*
1. Topic
   - F - Does not clearly articulate topic.
   - C - Describes topic.
   - B - Describes topic fully.
   - A - Describes topic and nuances.
2. Exposition
   - F - Does not fully describe topic.
   - C - Cursorily explains topic.
   - B - Explains topic and demonstrates knowledge of topic.
   - A - Explains topic and nuances and demonstrates knowledge of both.
3. Ethical Concerns
   - F - Does not articulate ethical concerns.
   - C - articulates ethical concerns on one side of the issue.
   - B - articulates ethical concerns one one side and opposing influences on other sides.
   - A - articulates ethical concerns on multiple sides.
4. Ethical justifications
   - F - Does not justify any side of the issue.
   - C - Justifies one side of the issue.
   - B - Justifies one side and explains an opposing view.
   - A - articulates arguments on multiple sides.
5. Coding Design (coding component required to recieve a passing grade on project)
   - F - No coding component.
   - C - Coding component is appropriately designed for selected topic.
   - B - Coding component is well designed to explore the selected topic.
   - A - Coding component is well designed, explores the topic and either further illuminates or reinforces the ethical justifications.
6. Coding Complexity
   - F - code does not include fundamental data structures / algorithms.
   - C - Code attempts to implement fundamental data structures / algorithms.
   - B - Code exhibits fundamental algorithm or data structures and runs.
   - A - Code exhibits complex algorithms and data structures and runs.
7. Coding Implementation
   - F - code does not run or does not implement stated design.
   - C - Code runs and exhibits stated design.
   - B - Code runs, exhibits stated design, demonstrates ethical issue.
   - A - Code runs, exhibits stated design, demonstrates ethical.
     issue, and is well structured/written.
 

** Deliverables:

    PDF of presentation (i.e., If you make a slide deck, export it to
    a PDF version.)  optional: slide deck or other content in its
    original format (slide deck, document, etc) Any code you use or
    cite.  Location/format: <reporoot>/final_project/*

    PDF of the paper.

    The code component

    All files should be placed in the final_project folder of both team member's repos on GitHub.
    
** Notes on the code aspect:

There must be a code component to your final project. This code
component does not have to be polished but it should be used to either
explore, illustrate your topic. It can be an implementation of
something related to the issue. For example, a program that splits
congressional districts or determines bail amount. It can also be
tangential. For example, if your issue has environmental concerns a
simulation that illustrates these issues.

You can use any programming language as long as the instructors can
run it. 

** Due Date:

November 30th, prior to the start of class (one week before the final class)

** Topic suggestions

If you want to do a topic not on the list, feel free to contact the
instructor.

Remember to fill out the form linked at the top once you've decided on partner and topic.
If you have any questions DM the instructor. If you submit the form and there's an issue with your choice of project, the instructors will contact you.

- Bias in data sets
- Loan algorithms
- Gaming  / Smartphone / Facebook addiction
- AI Authorship (copyright)
- AI Hiring practices in amazon 
- Open Source Software / Software licenses / EULAs
- predictive policing (see NYC Data mine or other data resources for stats)
- bail
- Value Added Metrics (VAM)
- gerrymandering 
- e-waste cycle / right to repair
- digital video in policing
- visually accesible web
- cryptocurrency emissions
- digital divide
- Right to repair
- planned obsolescence of smartphones
- password managers
- HS Matching algorithm (or other matching algos)
- Fake news
- randomware (sort of related are patent trolls) 
- Loan algorithms  
- Anything based on, spinning, or extending a class topic or ethicacy topic



